[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://buxdu.uz/api/:splat"
  status = 200
  force = true

[build.environment]
  REACT_APP_API_BASE_URL = "/api"


